/*=== Data ===*/

/* ==============================
   MENÚ DE CATEGORÍAS
============================== */

// Data de MENÚ  CATEGORÍAS
const categorias = {
  mujer: [
    {
      nombre: "Vestidos",
      img: "Assets/Mujer/Vestidos/vestidoRojo.png",
    },
    { nombre: "Blusas", img: "Assets/Mujer/Blusas/blusaAzul.png" },
    { nombre: "Faldas", img: "Assets/Mujer/Faldas/faldaNegra.png" },
    { nombre: "Pantalones", img: "Assets/Mujer/Pantalones/pantalonAzul.png" },
    { nombre: "Conjuntos", img: "Assets/Mujer/Conjuntos/conjuntoBlanco.png" },
    { nombre: "Accesorios", img: "Assets/Mujer/Accesorios/bolsoBlanco.png" },
  ],
  hombre: [
    { nombre: "Camisas", img: "Assets/Hombre/Camisas/camisaAzul.png" },
    { nombre: "Gorras", img: "Assets/Hombre/Gorras/gorraRoja.png" },
    { nombre: "Zapatos", img: "Assets/Hombre/Zapatos/zapatoNegro.png" },
    { nombre: "Pantalones", img: "Assets/Hombre/Pantalones/pantalonNegro.png" },
    {
      nombre: "Conjuntos",
      img: "Assets/Hombre/Conjuntos/conjuntoVioleta.png",
    },
    { nombre: "Accesorios", img: "Assets/Hombre/Accesorios/figurasAnime.png" },
  ],
};
/* ==============================
   CATÁLOGO Mujer
============================== */
// Data de SECCIÓN CATEGORÍAS con IDs, descripciones y precios
const dataMujeres = {
  vestidos: [
    {
      id: "MUJ-VES-001",
      src: "Assets/Mujer/Vestidos/vestidoAmarrillo.png",
      alt: "vestido Amarillo",
      descripcion:
        "Vestido Amarillo Largo Elegante de Color Sólido, Cuello en V.",
      precio: 45.99,
    },
    {
      id: "MUJ-VES-002",
      src: "Assets/Mujer/Vestidos/vestidoBlanco.png",
      alt: "vestido Blanco",
      descripcion: "Vestido  Blanco Elegante de Mujer con Cuello Cuadrado .",
      precio: 52.5,
    },
    {
      id: "MUJ-VES-003",
      src: "Assets/Mujer/Vestidos/vestidoAzul.png",
      alt: "vestido Azul",
      descripcion: "Vestido  Azul  Elegante de Primavera-Verano .",
      precio: 38.75,
    },
    {
      id: "MUJ-VES-004",
      src: "Assets/Mujer/Vestidos/vestidoNegro.png",
      alt: "vestido Blanco Con Rosado",
      descripcion: "Vestido Negro Elegante y Casual  con Escote Cuadrado.",
      precio: 47.25,
    },
    {
      id: "MUJ-VES-005",
      src: "Assets/Mujer/Vestidos/vestidoRojo.png",
      alt: "vestido Blanco Con Verde",
      descripcion: "Vestido Rojo , Mangas Largas, Silueta en A.",
      precio: 55.0,
    },
    {
      id: "MUJ-VES-006",
      src: "Assets/Mujer/Vestidos/vestidoNegroConBlanco.png",
      alt: "vestido Negro Con Blanco",
      descripcion:
        "Vestido negro  de Verano Elegante para Fiestas y Vacaciones.",
      precio: 49.99,
    },
    {
      id: "MUJ-VES-007",
      src: "Assets/Mujer/Vestidos/vestidoVerde.png",
      alt: "vestido Celeste",
      descripcion:
        "Vestido Verde Elegante ,  Ideal para Salidas, Citas y  Fiestas .",
      precio: 42.5,
    },
    {
      id: "MUJ-VES-008",
      src: "Assets/Mujer/Vestidos/vestidoPurpura.png",
      alt: "vestido Purpura",
      descripcion: "Vestido púrpura vibrante perfecto para fiestas nocturnas.",
      precio: 58.75,
    },
    {
      id: "MUJ-VES-009",
      src: "Assets/Mujer/Vestidos/vestidoRosado.png",
      alt: "vestido Rojo",
      descripcion: "Vestido Rosado Elegante vestido midi con cuello en V .",
      precio: 61.25,
    },
  ],
  blusas: [
    {
      id: "MUJ-BLU-001",
      src: "Assets/Mujer/Blusas/blusaAzul.png",
      alt: "blusa Azul",
      descripcion: "Blusa azul con Diseño Ajustado y Calado.",
      precio: 29.99,
    },
    {
      id: "MUJ-BLU-002",
      src: "Assets/Mujer/Blusas/blusaVerde.png",
      alt: "blusa Blanca Con Corazones",
      descripcion: "Blusa Verde De Cuello Con Forma Redonda .",
      precio: 34.5,
    },
    {
      id: "MUJ-BLU-003",
      src: "Assets/Mujer/Blusas/blusaBlancaConFlores.png",
      alt: "blusa Blanca Con Flores",
      descripcion: "Blusa blanca floral ideal para looks frescos.",
      precio: 32.75,
    },
    {
      id: "MUJ-BLU-004",
      src: "Assets/Mujer/Blusas/blusaMandarina.png",
      alt: "blusa Carmesi",
      descripcion: "Blusa Mandarina elegante de manga larga  con diseño hueco",
      precio: 39.99,
    },
    {
      id: "MUJ-BLU-005",
      src: "Assets/Mujer/Blusas/blusaNegra.png",
      alt: "blusa Negra",
      descripcion: "Blusa negra básica  esencial guardarropa .",
      precio: 27.5,
    },
    {
      id: "MUJ-BLU-006",
      src: "Assets/Mujer/Blusas/blusaPurpura.png",
      alt: "blusa Purpura",
      descripcion: "Blusa púrpura elegante perfecta ocasiones semi-formales.",
      precio: 36.25,
    },
    {
      id: "MUJ-BLU-007",
      src: "Assets/Mujer/Blusas/blusaRosada.png",
      alt: "blusa Rosada",
      descripcion: "Blusa rosada pastel con corte favorecedor todas tallas.",
      precio: 31.99,
    },
    {
      id: "MUJ-BLU-008",
      src: "Assets/Mujer/Blusas/blusaVerdeForforecense.png",
      alt: "blusa Verde",
      descripcion: "Blusa verde Forforecense  elegante manga larga.",
      precio: 33.75,
    },
    {
      id: "MUJ-BLU-009",
      src: "Assets/Mujer/Blusas/blusaMarron.png",
      alt: "blusa Marron",
      descripcion: "Blusa marrón elegante y con estilo.",
      precio: 35.5,
    },
  ],
  pantalones: [
    {
      id: "MUJ-PAN-001",
      src: "Assets/Mujer/Pantalones/pantalonAmarillo.png",
      alt: "pantalon Amarillo",
      descripcion: "Pantalón amarillo Ajustado de Imitación Denim para Mujer .",
      precio: 42.99,
    },
    {
      id: "MUJ-PAN-002",
      src: "Assets/Mujer/Pantalones/pantalonAzul.png",
      alt: "pantalon Azul",
      descripcion: "Pantalón azul con perlas y dobladillo.",
      precio: 39.75,
    },
    {
      id: "MUJ-PAN-003",
      src: "Assets/Mujer/Pantalones/pantalonBlanco.png",
      alt: "pantalon Blanco",
      descripcion: "Pantalón blanco d ajustado de talle alto .",
      precio: 44.5,
    },
    {
      id: "MUJ-PAN-004",
      src: "Assets/Mujer/Pantalones/pantalonCaqui.png",
      alt: "pantalon Caqui",
      descripcion: "Pantalón caqui  elegante, versátiles para todo",
      precio: 37.99,
    },
    {
      id: "MUJ-PAN-005",
      src: "Assets/Mujer/Pantalones/pantalonGris.png",
      alt: "pantalon Jean",
      descripcion: "Pantalón Gris  resistente duradero uso diario.",
      precio: 49.99,
    },
    {
      id: "MUJ-PAN-006",
      src: "Assets/Mujer/Pantalones/pantalonNegro.png",
      alt: "pantalon Negro",
      descripcion: "Pantalón negro elegante sofisticación para oficina.",
      precio: 52.25,
    },
    {
      id: "MUJ-PAN-007",
      src: "Assets/Mujer/Pantalones/pantalonRosado.png",
      alt: "pantalon Purpura",
      descripcion: "Pantalón púrpura  comodidad sin sacrificar estilo.",
      precio: 46.75,
    },
    {
      id: "MUJ-PAN-008",
      src: "Assets/Mujer/Pantalones/pantalonRojo.png",
      alt: "pantalon Rojo",
      descripcion: "Pantalón rojo llamativo declaración moda audaz.",
      precio: 48.5,
    },
    {
      id: "MUJ-PAN-009",
      src: "Assets/Mujer/Pantalones/pantalonVerde.png",
      alt: "pantalon Verde",
      descripcion:
        "Pantalón verde de traje de estilo chic para mujer en color liso.",
      precio: 41.99,
    },
  ],
  faldas: [
    {
      id: "MUJ-FAL-001",
      src: "Assets/Mujer/Faldas/faldaBlanca.png",
      alt: "falda Blanca",
      descripcion: "Falda blanca sirena de encaje en forma de cola de pez .",
      precio: 35.99,
    },
    {
      id: "MUJ-FAL-002",
      src: "Assets/Mujer/Faldas/faldaNegra.png",
      alt: "falda Negra",
      descripcion: "Falda Negra Minimalista de Línea A en Color Sólido",
      precio: 32.5,
    },
    {
      id: "MUJ-FAL-003",
      src: "Assets/Mujer/Faldas/faldaPurpura.png",
      alt: "falda Marron",
      descripcion: "Falda Purpura elegante y a la moda.",
      precio: 47.75,
    },
    {
      id: "MUJ-FAL-004",
      src: "Assets/Mujer/Faldas/faldaJean.png",
      alt: "falda Naranja",
      descripcion:
        "Falda Jean con estampado digital elegante y  estampado floral.",
      precio: 38.25,
    },
    {
      id: "MUJ-FAL-005",
      src: "Assets/Mujer/Faldas/faldaRoja.png",
      alt: "falda Negra",
      descripcion:
        "Falda Roja de Cintura Alta con Detalle de Botones, Falda Ajustada, Falda Midi.",
      precio: 29.99,
    },
    {
      id: "MUJ-FAL-006",
      src: "Assets/Mujer/Faldas/faldaAzul.png",
      alt: "falda Roja",
      descripcion:
        "Falda Azul para  fiesta diseño llamativo eventos especiales.",
      precio: 43.5,
    },
    {
      id: "MUJ-FAL-007",
      src: "Assets/Mujer/Faldas/faldaMandarina.png",
      alt: "falda Rosada",
      descripcion: "Falda mandarina Estilo Retro Vibrante y Elegante.",
      precio: 36.75,
    },
    {
      id: "MUJ-FAL-008",
      src: "Assets/Mujer/Faldas/faldaVerde.png",
      alt: "falda Turquesa",
      descripcion: "Falda turquesa verano ligera fresca días calurosos.",
      precio: 34.99,
    },
    {
      id: "MUJ-FAL-009",
      src: "Assets/Mujer/Faldas/faldaAmarilla.png",
      alt: "falda Verde",
      descripcion: "Falda amarilla Elegante falda midi para mujer",
      precio: 37.25,
    },
  ],
  conjuntos: [
    {
      id: "MUJ-CON-001",
      src: "Assets/Mujer/Conjuntos/conjuntoAmarillo.png",
      alt: "conjunto Amarillo",
      descripcion: "Conjunto amarillo de shorts de manga corta bordados .",
      precio: 68.99,
    },
    {
      id: "MUJ-CON-002",
      src: "Assets/Mujer/Conjuntos/conjuntoBlanco.png",
      alt: "conjunto Blanco",
      descripcion:
        "Conjunto blanco  - Top de Manga Corta con Cuello en V y Bloque de Color & Shorts Casuales.",
      precio: 72.5,
    },
    {
      id: "MUJ-CON-003",
      src: "Assets/Mujer/Conjuntos/conjuntoCeleste.png",
      alt: "conjunto Degradado",
      descripcion: "Conjunto Celeste con  diseño moderno vanguardista.",
      precio: 79.75,
    },
    {
      id: "MUJ-CON-004",
      src: "Assets/Mujer/Conjuntos/conjuntoGris.png",
      alt: "conjunto Gris",
      descripcion:
        "Conjunto gris de top y pantalón de color liso y corte ajustado.",
      precio: 65.99,
    },
    {
      id: "MUJ-CON-005",
      src: "Assets/Mujer/Conjuntos/conjuntoNegro.png",
      alt: "conjunto Negro",
      descripcion: "Conjunto negro fiesta ideal eventos nocturnos especiales.",
      precio: 84.5,
    },
    {
      id: "MUJ-CON-006",
      src: "Assets/Mujer/Conjuntos/conjuntoPurpura.png",
      alt: "conjunto Purpura",
      descripcion: "Conjunto púrpura elegante perfecto ocasiones formales.",
      precio: 76.25,
    },
    {
      id: "MUJ-CON-007",
      src: "Assets/Mujer/Conjuntos/conjuntoRojo.png",
      alt: "conjunto Rojo",
      descripcion: "Conjunto rojo elegante , ideal para primavera y verano.",
      precio: 88.99,
    },
    {
      id: "MUJ-CON-008",
      src: "Assets/Mujer/Conjuntos/conjuntoRosado.png",
      alt: "conjunto Rosado",
      descripcion:
        "Conjunto rosado casual  de manga corta y pantalones largos .",
      precio: 71.75,
    },
    {
      id: "MUJ-CON-009",
      src: "Assets/Mujer/Conjuntos/conjuntoVerde.png",
      alt: "conjunto Verde",
      descripcion:
        "Conjunto verde Casual de Verano - Un Set de Dos Piezas con un Top de Cuello Redondo.",
      precio: 74.5,
    },
  ],
  accesorios: [
    {
      id: "MUJ-ACC-001",
      src: "Assets/Mujer/Accesorios/anilloCompromiso.png",
      alt: "anillo Compromiso",
      descripcion: "Anillo compromiso diamante central símbolo amor eterno.",
      precio: 299.99,
    },
    {
      id: "MUJ-ACC-002",
      src: "Assets/Mujer/Accesorios/bolsoBlanco.png",
      alt: "bolso Blanco",
      descripcion: "Bolso blanco ,  Tote de Moda con Relieve.",
      precio: 45.5,
    },
    {
      id: "MUJ-ACC-003",
      src: "Assets/Mujer/Accesorios/collarLunaConSOl.png",
      alt: "collar Luna Con SOl",
      descripcion: "Collar colgante luna sol diseño místico espiritual.",
      precio: 28.75,
    },
    {
      id: "MUJ-ACC-004",
      src: "Assets/Mujer/Accesorios/gafasOvaladas.png",
      alt: "gafas Ovaladas",
      descripcion: "Gafas sol ovaladas estilo retro nunca pasa moda.",
      precio: 32.99,
    },
    {
      id: "MUJ-ACC-005",
      src: "Assets/Mujer/Accesorios/juegoGorroGuantesBufandaLanaRojo.png",
      alt: "juego Gorro Guantes Bufanda Lana Rojo",
      descripcion: "Conjunto 3 piezas - Gorro rojo , bufanda y guantes .",
      precio: 39.99,
    },
    {
      id: "MUJ-ACC-006",
      src: "Assets/Mujer/Accesorios/juegoPulseraCollarAretes.png",
      alt: "juego Pulsera Collar Aretes",
      descripcion: "Juego joyería coordinada elegancia completa solo set.",
      precio: 52.25,
    },
    {
      id: "MUJ-ACC-007",
      src: "Assets/Mujer/Accesorios/relojRosado.png",
      alt: "reloj Rosado",
      descripcion: "Reloj rosado correa silicona perfecto deporte día.",
      precio: 67.5,
    },
    {
      id: "MUJ-ACC-008",
      src: "Assets/Mujer/Accesorios/sobreroSol.png",
      alt: "Sobrero SOl",
      descripcion: "Un Sombrero de Paja de Verano para Mujer",
      precio: 29.75,
    },
    {
      id: "MUJ-ACC-009",
      src: "Assets/Mujer/Accesorios/setPintaLabios.png",
      alt: "Set Pinta Labios",
      descripcion: "Set de 8 labiales líquidos mate de Leaf Poem",
      precio: 58.99,
    },
  ],
};
/* ==============================
   CATÁLOGO Hombres
============================== */
// Data de SECCIÓN CATEGORÍAS con IDs, descripciones y precios
const dataHombres = {
  camisas: [
    {
      id: "HOM-CAM-001",
      src: "Assets/Hombre/Camisas/camisaAmarilla.png",
      alt: "camisa Amarilla",
      descripcion: "Camisa amarilla de golf para hombre con estampado  .",
      precio: 34.99,
    },
    {
      id: "HOM-CAM-002",
      src: "Assets/Hombre/Camisas/camisaAzul.png",
      alt: "camisa Azul",
      descripcion: "Camisa azul de Manga Corta con Estampado para Hombres",
      precio: 42.5,
    },
    {
      id: "HOM-CAM-003",
      src: "Assets/Hombre/Camisas/camisaBlanca.png",
      alt: "camisa Blanca",
      descripcion: "Camisa blanca clásica versátil elegante cualquier ocasión.",
      precio: 38.75,
    },
    {
      id: "HOM-CAM-004",
      src: "Assets/Hombre/Camisas/camisaGris.png",
      alt: "camisa Gris",
      descripcion: "Camisa gris trabajo profesional cómoda oficina.",
      precio: 36.25,
    },
    {
      id: "HOM-CAM-005",
      src: "Assets/Hombre/Camisas/camisaNegra.png",
      alt: "camisa Negra",
      descripcion: "Camisa negra fiesta ideal eventos nocturnos formales.",
      precio: 45.99,
    },
    {
      id: "HOM-CAM-006",
      src: "Assets/Hombre/Camisas/camisaPurpura.png",
      alt: "camisa Purpura",
      descripcion: "Camisa púrpura Casual de Golf  con Estampado Digital .",
      precio: 39.5,
    },
    {
      id: "HOM-CAM-007",
      src: "Assets/Hombre/Camisas/camisaRoja.png",
      alt: "camisa Roja",
      descripcion: "Camisa roja vibrante perfecta destacar cualquier reunión.",
      precio: 41.75,
    },
    {
      id: "HOM-CAM-008",
      src: "Assets/Hombre/Camisas/camisaRosada.png",
      alt: "camisa Rosada",
      descripcion: "Camisa rosada pastel tendencia moderna moda masculina.",
      precio: 37.99,
    },
    {
      id: "HOM-CAM-009",
      src: "Assets/Hombre/Camisas/camisaVerde.png",
      alt: "camisa Verde",
      descripcion: "Camisa verde  con cuello abotonado diseño cómodo .",
      precio: 35.5,
    },
  ],
  pantalones: [
    {
      id: "HOM-PAN-001",
      src: "Assets/Hombre/Pantalones/pantalonAmarillo.png",
      alt: "pantalon Amarillo",
      descripcion: "Pantalón amarillo Vaqueros  para Uso Diario y Formal.",
      precio: 44.99,
    },
    {
      id: "HOM-PAN-002",
      src: "Assets/Hombre/Pantalones/pantalonAzul.png",
      alt: "pantalon Azul",
      descripcion: "Pantalón azul Pantalones de mezclilla de moda para hombre.",
      precio: 52.5,
    },
    {
      id: "HOM-PAN-003",
      src: "Assets/Hombre/Pantalones/pantalonBlanco.png",
      alt: "pantalon Blanco",
      descripcion: "Pantalón blanco lino perfecto climas cálidos frescos.",
      precio: 47.75,
    },
    {
      id: "HOM-PAN-004",
      src: "Assets/Hombre/Pantalones/pantalonCaqui.png",
      alt: "pantalon Caqui",
      descripcion: "Pantalón caqui estilo chino versátil cómodo día.",
      precio: 41.99,
    },
    {
      id: "HOM-PAN-005",
      src: "Assets/Hombre/Pantalones/pantalonGris.png",
      alt: "pantalon Gris",
      descripcion: "Pantalón gris sportwear ideal looks casuales modernos.",
      precio: 46.25,
    },
    {
      id: "HOM-PAN-006",
      src: "Assets/Hombre/Pantalones/pantalonJean.png",
      alt: "pantalon Jean",
      descripcion: "Pantalón jean clásico duradero esencial cualquier armario.",
      precio: 49.99,
    },
    {
      id: "HOM-PAN-007",
      src: "Assets/Hombre/Pantalones/pantalonNegro.png",
      alt: "pantalon Negro",
      descripcion: "Pantalón negro vestir sofisticación ocasiones formales.",
      precio: 54.5,
    },
    {
      id: "HOM-PAN-008",
      src: "Assets/Hombre/Pantalones/pantalonRojo.png",
      alt: "pantalon Rojo",
      descripcion: "Pantalón rojo deportivo hombres buscan destacar.",
      precio: 48.75,
    },
    {
      id: "HOM-PAN-009",
      src: "Assets/Hombre/Pantalones/pantalonVerde.png",
      alt: "pantalon Verde",
      descripcion:
        "Pantalón verde deportivos largos  estilo casual y deportivo,",
      precio: 43.99,
    },
  ],
  gorras: [
    {
      id: "HOM-GOR-001",
      src: "Assets/Hombre/Gorras/gorraAmarilla.png",
      alt: "gorra Amarilla",
      descripcion: "Gorra amarilla deportiva protección solar estilo urbano.",
      precio: 19.99,
    },
    {
      id: "HOM-GOR-002",
      src: "Assets/Hombre/Gorras/gorraAzul.png",
      alt: "gorra Azul",
      descripcion: "Gorra azul clásica diseño simple efectivo día.",
      precio: 17.5,
    },
    {
      id: "HOM-GOR-003",
      src: "Assets/Hombre/Gorras/gorraBeige.png",
      alt: "gorra Beige",
      descripcion: "Gorra beige neutra combina cualquier outfit casual.",
      precio: 18.75,
    },
    {
      id: "HOM-GOR-004",
      src: "Assets/Hombre/Gorras/gorraBlanca.png",
      alt: "gorra Blanca",
      descripcion: "Gorra blanca básica esencial looks veraniegos.",
      precio: 16.99,
    },
    {
      id: "HOM-GOR-005",
      src: "Assets/Hombre/Gorras/gorraGris.png",
      alt: "gorra Gris",
      descripcion: "Gorra gris moderna estilo minimalista hombres urbanos.",
      precio: 20.25,
    },
    {
      id: "HOM-GOR-006",
      src: "Assets/Hombre/Gorras/gorraNegra.png",
      alt: "gorra Negra",
      descripcion: "Gorra negra universal nunca pasa moda combina.",
      precio: 18.5,
    },
    {
      id: "HOM-GOR-007",
      src: "Assets/Hombre/Gorras/gorraRoja.png",
      alt: "gorra Roja",
      descripcion: "Gorra roja vibrante destacar cualquier multitud.",
      precio: 21.75,
    },
    {
      id: "HOM-GOR-008",
      src: "Assets/Hombre/Gorras/gorraRosada.png",
      alt: "gorra Rosada",
      descripcion: "Gorra rosada moderna tendencia moda masculina actual.",
      precio: 19.25,
    },
    {
      id: "HOM-GOR-009",
      src: "Assets/Hombre/Gorras/gorraVerde.png",
      alt: "gorra Verde",
      descripcion: "Gorra verde militar estilo casual toque urbano.",
      precio: 17.99,
    },
  ],
  zapatos: [
    {
      id: "HOM-ZAP-001",
      src: "Assets/Hombre/Zapatos/zapatoAmarillo.png",
      alt: "zapato Amarillo",
      descripcion: "Zapatos amarillos casuales perfectos looks deportivos.",
      precio: 59.99,
    },
    {
      id: "HOM-ZAP-002",
      src: "Assets/Hombre/Zapatos/zapatoAzul.png",
      alt: "zapato Azul",
      descripcion: "Zapatos azules vestir elegancia comodidad oficina.",
      precio: 67.5,
    },
    {
      id: "HOM-ZAP-003",
      src: "Assets/Hombre/Zapatos/zapatoCaqui.png",
      alt: "zapato Caqui",
      descripcion: "Zapatos caqui casuales versátiles cómodos día.",
      precio: 54.75,
    },
    {
      id: "HOM-ZAP-004",
      src: "Assets/Hombre/Zapatos/zapatoBlanco.png",
      alt: "zapato Blanco",
      descripcion: "Zapatos blancos deportivos clásicos nunca pasan moda.",
      precio: 62.99,
    },
    {
      id: "HOM-ZAP-005",
      src: "Assets/Hombre/Zapatos/zapatogris.png",
      alt: "zapatogris",
      descripcion:
        "Zapatos gris modernos diseño contemporáneo hombres urbanos.",
      precio: 58.25,
    },
    {
      id: "HOM-ZAP-006",
      src: "Assets/Hombre/Zapatos/zapatoNegro.png",
      alt: "zapato Negro",
      descripcion: "Zapatos negros para eventos importantes.",
      precio: 72.5,
    },
    {
      id: "HOM-ZAP-007",
      src: "Assets/Hombre/Zapatos/zapatoPurpura.png",
      alt: "zapato Purpura",
      descripcion: "Zapatos púrpura modernos hombres atreven color.",
      precio: 65.75,
    },
    {
      id: "HOM-ZAP-008",
      src: "Assets/Hombre/Zapatos/zapatoRojo.png",
      alt: "zapato Rojo",
      descripcion:
        "Zapatos rojos llamativos perfectos destacar cualquier evento.",
      precio: 69.99,
    },
    {
      id: "HOM-ZAP-009",
      src: "Assets/Hombre/Zapatos/zapatoVerdeClaro.png",
      alt: "zapato Verde Claro ",
      descripcion:
        "Zapatos verdes claro casuales tendencia calzado masculino urbano.",
      precio: 61.5,
    },
  ],
  conjuntos: [
    {
      id: "HOM-CON-001",
      src: "Assets/Hombre/Conjuntos/conjuntoAmarillo.png",
      alt: "conjunto Amarillo",
      descripcion: "Conjunto amarillo deportivo looks casuales.",
      precio: 78.99,
    },
    {
      id: "HOM-CON-002",
      src: "Assets/Hombre/Conjuntos/conjuntoAzul.png",
      alt: "conjunto Azul",
      descripcion:
        "Conjunto azul marino elegante ideal ocasiones semi-formales.",
      precio: 85.5,
    },
    {
      id: "HOM-CON-003",
      src: "Assets/Hombre/Conjuntos/conjuntoBlanco.png",
      alt: "conjunto Blanco",
      descripcion: "Conjunto blanco minimalista frescura estilo verano.",
      precio: 79.75,
    },
    {
      id: "HOM-CON-004",
      src: "Assets/Hombre/Conjuntos/conjuntoNegro.png",
      alt: "conjunto  Negro",
      descripcion: "Conjunto  negro contrastante diseño moderno atemporal.",
      precio: 92.25,
    },
    {
      id: "HOM-CON-005",
      src: "Assets/Hombre/Conjuntos/conjuntoGris.png",
      alt: "conjunto Gris",
      descripcion: "Conjunto gris sportwear comodidad estilo urbano.",
      precio: 76.99,
    },
    {
      id: "HOM-CON-006",
      src: "Assets/Hombre/Conjuntos/conjuntoCaqui.png",
      alt: "conjunto Caqui",
      descripcion: "Conjunto Caqui detalles sofisticación moderna.",
      precio: 88.5,
    },
    {
      id: "HOM-CON-007",
      src: "Assets/Hombre/Conjuntos/conjuntoVioleta.png",
      alt: "conjunto Violeta ",
      descripcion:
        "Conjunto Violeta de Sudadera con Cuello Redondo y Pantalónes .",
      precio: 84.75,
    },
    {
      id: "HOM-CON-008",
      src: "Assets/Hombre/Conjuntos/conjuntoRojo.png",
      alt: "conjunto Rojo",
      descripcion: "Conjunto rojo deportivo energía estilo hombres activos.",
      precio: 91.99,
    },
    {
      id: "HOM-CON-009",
      src: "Assets/Hombre/Conjuntos/conjuntoVerde.png",
      alt: "conjunto Verde",
      descripcion: "Conjunto verde militar estilo urbano inspiración outdoor.",
      precio: 82.5,
    },
  ],
  accesorios: [
    {
      id: "HOM-ACC-001",
      src: "Assets/Hombre/Accesorios/billetera.png",
      alt: "billetera",
      descripcion: "Billetera cuero genuino diseño elegante funcional.",
      precio: 34.99,
    },
    {
      id: "HOM-ACC-002",
      src: "Assets/Hombre/Accesorios/figurasAnime.png",
      alt: "figuras Anime",
      descripcion: "Figuras coleccionables anime fans coleccionistas.",
      precio: 42.5,
    },
    {
      id: "HOM-ACC-003",
      src: "Assets/Hombre/Accesorios/gafasRectagular.png",
      alt: "gafas Rectagular",
      descripcion: "Gafas sol rectangulares estilo retro moderno.",
      precio: 28.75,
    },
    {
      id: "HOM-ACC-004",
      src: "Assets/Hombre/Accesorios/guantes.png",
      alt: "guantes",
      descripcion: "Guantes cuero moto protección estilo urbano.",
      precio: 39.99,
    },
    {
      id: "HOM-ACC-005",
      src: "Assets/Hombre/Accesorios/JuegoCadenaPulsera.png",
      alt: "Juego Cadena Pulsera",
      descripcion: "Juego cadena y  pulsera modernos.",
      precio: 47.25,
    },
    {
      id: "HOM-ACC-006",
      src: "Assets/Hombre/Accesorios/mancuernas.png",
      alt: "mancuernas",
      descripcion: "Mancuernas ajustables entrenamiento casa.",
      precio: 65.5,
    },
    {
      id: "HOM-ACC-007",
      src: "Assets/Hombre/Accesorios/mochila.png",
      alt: "mochila",
      descripcion: "Mochila urbana resistente perfecta día.",
      precio: 52.75,
    },
    {
      id: "HOM-ACC-008",
      src: "Assets/Hombre/Accesorios/perfume.png",
      alt: "perfume",
      descripcion: "Perfume masculino  fragancia duradera .",
      precio: 58.99,
    },
    {
      id: "HOM-ACC-009",
      src: "Assets/Hombre/Accesorios/relojNegro.png",
      alt: "reloj Negro",
      descripcion: "Reloj negro deportivo funcionalidad estilo moderno.",
      precio: 74.5,
    },
  ],
};

export { dataMujeres, dataHombres, categorias };
